deploy-steps: &deploy-steps
  - attach_workspace:
      at: ~/circleci-deployment
  - run:
      name: Build Docker
      command: |
        docker login -u $DOCKER_USER -p $DOCKER_PASS
        docker build -f docker/Dockerfile -t bespoken/bst:$CIRCLE_TAG .
        docker push bespoken/bst:$CIRCLE_TAG
  - run:
      name: Deploy container
      command: |
        sudo npm install fargate-helper -g
        if [ "$TYPE_OF_DEPLOY" == "server" ]; then
          fargate service \
            --command "node bin/bst-server.js start 443 5000" \
            --containerPort 5000 \
            --cpu 1024 \
            --env AWS_ACCESS_KEY_ID=$PROD_AWS_ACCESS_KEY_ID \
            --env AWS_SECRET_ACCESS_KEY=$PROD_AWS_SECRET_ACCESS_KEY \
            --env SSL_CERT=$SSL_CERT \
            --env SSL_KEY=$SSL_KEY \
            --env SOURCE_API_URL=$SOURCE_API_URL_PROD \
            --image bespoken/bst:$CIRCLE_TAG \
            --memory 2048 \
            --name bst
        else
          fargate service \
            --command "node bin/bst-server.js start 443 5000" \
            --containerPort 5000 \
            --cpu 512 \
            --env AWS_ACCESS_KEY_ID=$PROD_AWS_ACCESS_KEY_ID \
            --env AWS_SECRET_ACCESS_KEY=$PROD_AWS_SECRET_ACCESS_KEY \
            --env SSL_CERT=$SSL_CERT \
            --env SSL_KEY=$SSL_KEY \
            --env SOURCE_API_URL=$SOURCE_API_URL_DEV \
            --image bespoken/bst:$CIRCLE_TAG \
            --memory 1024 \
            --name bst-dev
        fi

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/circleci-deployment
    steps:
      - attach_workspace:
          at: ~/circleci-deployment
      - checkout
      - run: npm install
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths: .
  test:
    docker:
      - image: circleci/node:8
    working_directory: ~/circleci-deployment
    steps:
      - attach_workspace:
          at: ~/circleci-deployment
      - checkout
      - run: npm install
      - run: npm run test
      - persist_to_workspace:
          root: .
          paths: .

  codecov:
    machine: true
    environment:
      - SKIP_STATISTICS: "true"
    working_directory: ~/circleci-deployment
    steps:
      - attach_workspace:
          at: ~/circleci-deployment
      - run: npm run codecov
      - persist_to_workspace:
          root: .
          paths: .
  bst-dev:
    docker:
      - image: circleci/node:8
    environment:
      - TYPE_OF_DEPLOY: dev
      - SKIP_STATISTICS: "true"

    working_directory: ~/circleci-deployment
    steps: *deploy-steps

  bst-server:
    machine: true
    environment:
      - TYPE_OF_DEPLOY: server
      - SKIP_STATISTICS: "true"

    working_directory: ~/circleci-deployment
    steps: *deploy-steps


workflows:
  version: 2
  test-n-deploy:
    jobs:
      - bst-dev:
          requires:
            - build
          filters:
            tags:
              only: /bst-dev-.*/
            branches:
              ignore: /.*/
      - bst-server:
          requires:
            - test
          filters:
            tags:
              only: /bst-server-.*/
            branches:
              ignore: /.*/